services:
  scala:
    build: .
    ports:
      - "8000:9000"
    networks:
      - backend
  ngrok:
    image: ngrok/ngrok:latest
    command:
      - "http"
      - "scala:9000"
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    ports:
      - 4040:4040
    networks:
      - backend

networks:
  backend:
