name: Deploy Server

env:
  AZURE_WEBAPP_NAME: ebiznes-back-end

on:
  push:
    paths:
      - 'Frontend/server/**'

permissions:
  contents: 'read'
  packages: 'write'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
          
      - name: Install dependencies
        run: go get .
        working-directory: ./Frontend/server

      - name: Test with the Go CLI
        run: go test -v ./...
        working-directory: ./Frontend/server

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Lowercase the repo name
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/${{ env.REPO }}/server:${{ github.sha }}
          file: Frontend/server/Dockerfile
          context: ./Frontend/server
  
  build-notify:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Send mail
        uses: dawidd6/action-send-mail@v5
        with:
          server_address: ${{ secrets.SMTP_ADDRESS }}
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Build Client (${{ github.repository }}) — ${{ needs.build.result }}
          body: The build has been finished with ${{ needs.build.result }} status.
          to: ${{ secrets.TO_EMAIL }}
          from: ${{ secrets.FROM_NAME }}
          
  deploy:
    runs-on: ubuntu-latest

    needs: build

    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Lowercase the repo name
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_SERVER_WEBAPP_PUBLISH_PROFILE }}
          images: 'ghcr.io/${{ env.REPO }}/server:${{ github.sha }}'