name: Deploy Client

on:
  push:
    paths:
      - 'Frontend/client/**'

permissions:
  contents: 'read'
  packages: 'write'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Lowercase the repo name
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/${{ env.REPO }}/client:${{ github.sha }}
          file: Frontend/client/Dockerfile
          context: ./Frontend/client
          
  build-notify:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Send Email Notification
        run: |
          curl -s -X POST --user "${{ secrets.MAILJET_API_KEY }}:${{ secrets.MAILJET_API_SECRET }}" \
          https://api.mailjet.com/v3/send \
          -H 'Content-Type: application/json' \
          -d "{
            \"FromEmail\": \"${{ secrets.FROM_EMAIL }}\",
            \"FromName\": \"${{ secrets.FROM_NAME }}\",
            \"Subject\": \"Build Result\",
            \"Text-part\": \"Build result: ${{ needs.build.result }}\",
            \"Recipients\": [{\"Email\": \"${{ secrets.EMAIL_TO }}\"}]
          }"
          