name: Deploy Client

on:
  push:
    paths:
      - 'Frontend/client/**'

permissions:
  contents: 'read'
  packages: 'write'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Lowercase the repo name
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/${{ env.REPO }}/client:${{ github.sha }}
          file: Frontend/client/Dockerfile
          context: ./Frontend/client
          
  build-notify:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Send mail
        uses: dawidd6/action-send-mail@v5
        with:
          server_address: ${{ secrets.SMTP_ADDRESS }}
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Build Client (${{ github.repository }}) — ${{ needs.build.result }}
          body: The build has been finished with ${{ needs.build.result }} status.
          to: ${{ secrets.TO_EMAIL }}
          from: ${{ secrets.FROM_NAME }}