name: Run Linters

on:
  push:
    branches:
      - main

env:
  GO_VERSION: stable
  GOLANGCI_LINT_VERSION: v2.1
  GO_APP_DIRECTORY: ./Frontend/server

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache-dependency-path: ${{ env.GO_APP_DIRECTORY }}
      - uses: golangci/golangci-lint-action@v8
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}
          working-directory: ${{ env.GO_APP_DIRECTORY }}
