name: Run Linters

on:
  push:
    branches:
      - main

env:
  GO_VERSION: stable
  GOLANGCI_LINT_VERSION: v2.1

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Frontend/server
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: golangci/golangci-lint-action@v8
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}
